markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Kun 's Home
description: Blog depend of Jekyll AND Theme design by zhan
keywords: Jekyll Theme
url: http://pizn.github.io/kunka
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html

#Author config
author:
    name: kun
    email: j2211@QQ.com
    imageLink: http://i2.sinaimg.cn/ent/v/2008-01-21/U2411P28T3D1885976F326DT20080121181126.jpg
    simpleIntro: 我是「kun」，欢迎来到这儿
    detailIntro:
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>
      <p>很早之前，使用过 wordpress 来写博客。但是还要处理很多的底层问题。而使用 Jekyll 来写博客，可以很简单，写 Markdown 就好。然而，Jekyll 还很年轻，没有很多主题的支持。这里的主题，就是为 Jekyll 而写的。希望你能喜欢。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-weibo
    url: http://weibo.com/pizn
  - class: icon-github-alt
    url: http://github.com/pizn

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends


#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: kun